# Generated by Django 5.1.2 on 2024-12-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_date_created_alter_customer_email_and_more'),
        ('app', '0003_remove_customer_is_admin_customer_user'),
    ]

    operations = [
    ]
