# Generated by Django 5.1.2 on 2024-12-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_assignment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='people_involved',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
