# Generated by Django 5.1.2 on 2024-12-08 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_assignment_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
